{
  "total_campos": 43,
  "campos_validos": 9,
  "campos_invalidos": 34,
  "taxa_sucesso": 20.930232558139537,
  "lista_campos_validos": [
    "product_uom_qty",
    "qty_to_invoice",
    "qty_saldo",
    "qty_cancelado",
    "qty_invoiced",
    "price_unit",
    "l10n_br_prod_valor",
    "l10n_br_total_nfe",
    "qty_delivered"
  ],
  "lista_campos_invalidos": [
    "order_id/l10n_br_pedido_compra",
    "order_id/name",
    "order_id/create_date",
    "order_id/date_order",
    "order_id/partner_id/l10n_br_cnpj",
    "order_id/partner_id/l10n_br_razao_social",
    "order_id/partner_id/name",
    "order_id/partner_id/l10n_br_municipio_id/name",
    "order_id/partner_id/state_id/code",
    "order_id/user_id",
    "order_id/team_id",
    "product_id/default_code",
    "product_id/name",
    "product_id/uom_id",
    "order_id/state",
    "product_id/categ_id/name",
    "product_id/categ_id/parent_id/name",
    "product_id/categ_id/parent_id/parent_id/name",
    "order_id/payment_term_id",
    "order_id/payment_provider_id",
    "order_id/picking_note",
    "order_id/incoterm",
    "order_id/carrier_id",
    "order_id/commitment_date",
    "order_id/partner_id/agendamento",
    "order_id/partner_shipping_id/l10n_br_cnpj",
    "order_id/partner_shipping_id/self",
    "order_id/partner_shipping_id/zip",
    "order_id/partner_shipping_id/state_id",
    "order_id/partner_shipping_id/l10n_br_municipio_id",
    "order_id/partner_shipping_id/l10n_br_endereco_bairro",
    "order_id/partner_shipping_id/street",
    "order_id/partner_shipping_id/l10n_br_endereco_numero",
    "order_id/partner_shipping_id/phone"
  ],
  "detalhes_completos": [
    {
      "campo": "order_id/l10n_br_pedido_compra",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/l10n_br_pedido_compra\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/name",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/name\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/create_date",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/create_date\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/date_order",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/date_order\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/partner_id/l10n_br_cnpj",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/partner_id/l10n_br_cnpj\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/partner_id/l10n_br_razao_social",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/partner_id/l10n_br_razao_social\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/partner_id/name",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/partner_id/name\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/partner_id/l10n_br_municipio_id/name",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/partner_id/l10n_br_municipio_id/name\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/partner_id/state_id/code",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/partner_id/state_id/code\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/user_id",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/user_id\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/team_id",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/team_id\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "product_id/default_code",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'product_id/default_code\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "product_id/name",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'product_id/name\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "product_id/uom_id",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'product_id/uom_id\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "product_uom_qty",
      "valido": true,
      "valor_exemplo": 10.0,
      "tipo_valor": "float",
      "erro": null
    },
    {
      "campo": "qty_to_invoice",
      "valido": true,
      "valor_exemplo": 0.0,
      "tipo_valor": "float",
      "erro": null
    },
    {
      "campo": "qty_saldo",
      "valido": true,
      "valor_exemplo": 10.0,
      "tipo_valor": "float",
      "erro": null
    },
    {
      "campo": "qty_cancelado",
      "valido": true,
      "valor_exemplo": 0.0,
      "tipo_valor": "float",
      "erro": null
    },
    {
      "campo": "qty_invoiced",
      "valido": true,
      "valor_exemplo": 0.0,
      "tipo_valor": "float",
      "erro": null
    },
    {
      "campo": "price_unit",
      "valido": true,
      "valor_exemplo": 179.87,
      "tipo_valor": "float",
      "erro": null
    },
    {
      "campo": "l10n_br_prod_valor",
      "valido": true,
      "valor_exemplo": 1798.7,
      "tipo_valor": "float",
      "erro": null
    },
    {
      "campo": "l10n_br_total_nfe",
      "valido": true,
      "valor_exemplo": 1798.7,
      "tipo_valor": "float",
      "erro": null
    },
    {
      "campo": "order_id/state",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/state\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "product_id/categ_id/name",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'product_id/categ_id/name\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "product_id/categ_id/parent_id/name",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'product_id/categ_id/parent_id/name\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "product_id/categ_id/parent_id/parent_id/name",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'product_id/categ_id/parent_id/parent_id/name\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/payment_term_id",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/payment_term_id\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/payment_provider_id",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/payment_provider_id\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/picking_note",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/picking_note\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/incoterm",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/incoterm\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/carrier_id",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/carrier_id\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/commitment_date",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/commitment_date\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/partner_id/agendamento",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/partner_id/agendamento\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "qty_delivered",
      "valido": true,
      "valor_exemplo": 0.0,
      "tipo_valor": "float",
      "erro": null
    },
    {
      "campo": "order_id/partner_shipping_id/l10n_br_cnpj",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/partner_shipping_id/l10n_br_cnpj\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/partner_shipping_id/self",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/partner_shipping_id/self\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/partner_shipping_id/zip",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/partner_shipping_id/zip\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/partner_shipping_id/state_id",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/partner_shipping_id/state_id\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/partner_shipping_id/l10n_br_municipio_id",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/partner_shipping_id/l10n_br_municipio_id\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/partner_shipping_id/l10n_br_endereco_bairro",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/partner_shipping_id/l10n_br_endereco_bairro\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/partner_shipping_id/street",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/partner_shipping_id/street\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/partner_shipping_id/l10n_br_endereco_numero",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/partner_shipping_id/l10n_br_endereco_numero\\' on model \\'sale.order.line\\'\\n'>"
    },
    {
      "campo": "order_id/partner_shipping_id/phone",
      "valido": false,
      "valor_exemplo": null,
      "tipo_valor": null,
      "erro": "<Fault 1: 'Traceback (most recent call last):\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 151, in xmlrpc_2\\n    response = self._xmlrpc(service)\\n  File \"/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py\", line 127, in _xmlrpc\\n    result = dispatch_rpc(service, method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/http.py\", line 389, in dispatch_rpc\\n    return dispatch(method, params)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 56, in dispatch\\n    res = execute_kw(db, uid, *params[3:])\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 79, in execute_kw\\n    return execute(db, uid, obj, method, *args, **kw or {})\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 84, in execute\\n    res = execute_cr(cr, uid, obj, method, *args, **kw)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 70, in execute_cr\\n    result = retrying(partial(odoo.api.call_kw, recs, method, args, kw), env)\\n  File \"/usr/lib/python3/dist-packages/odoo/service/model.py\", line 152, in retrying\\n    result = func()\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 480, in call_kw\\n    result = _call_kw_model(method, model, args, kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/api.py\", line 451, in _call_kw_model\\n    result = method(recs, *args, **kwargs)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 5787, in search_read\\n    records = self.search_fetch(domain or [], fields, offset=offset, limit=limit, order=order)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 1652, in search_fetch\\n    fields_to_fetch = self._determine_fields_to_fetch(field_names)\\n  File \"/usr/lib/python3/dist-packages/odoo/models.py\", line 3910, in _determine_fields_to_fetch\\n    raise ValueError(f\"Invalid field {field_name!r} on model {self._name!r}\")\\nValueError: Invalid field \\'order_id/partner_shipping_id/phone\\' on model \\'sale.order.line\\'\\n'>"
    }
  ]
}